name: "Compendium universalis"

description: "Konny's compendium of wisdom, ideas and knowledge"

url: "http://localhost:4000"

paginate: 10

markdown: kramdown

highlighter: pygments

permalink: pretty

github:
    repo: github.com/kordano/kordano.github.io

pages_list:
    archive: '/archive/'
    about: '/about/'
