name: "(inc knowledge)"
description: "Kordano's thought collection"

url: "http://localhost:4000"

paginate: 10

markdown: redcarpet

pygments: true

permalink: pretty

github:
 repo: github.com/kordano/kordano.github.io

pages_list:
  archive: '/archive/'
  about: '/about/'

sass:
  sass_dir: _sass