name: "(inc knowledge)"
description: "Konrad Kühne's web presence"

url: "http://localhost:4000"

paginate: 10

markdown: redcarpet

highlighter: pygments

permalink: pretty

github: 
    repo: github.com/kordano/kordano.github.io

pages_list: 
    archive: '/archive/'
    about: '/about/'
