name: "Konrad Kühne"

description: "Creating the future cloud"

url: "http://localhost:4000"

paginate: 10

markdown: kramdown

highlighter: pygments

permalink: pretty

github:
    repo: github.com/kordano/kordano.github.io

pages_list:
    about: '/about/'
